# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codice Inutile
email: codiceinutile@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Codice Inutile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.codiceinutile.org" # the base hostname & protocol for your site
twitter_username: codiceinutile
github_username:  codiceinutile

# Build settings
markdown: kramdown

# SEO
gems:
  - jekyll-seo-tag
